src/components/navigation/Breadcrumbs.tsx, src/theme.tsx
=> Breadcrumbs updates

src/components/content/Horizon.tsx, src/components/navigation/Footer.tsx, src/components/navigation/FooterNav.tsx, src/helper/csshelper.ts, src/theme.tsx
=> Footer style changes

src/components/navigation/Breadcrumbs.tsx
fixes #11
- smaller font size
- `…` when more than 4 items
=> Breadcrumbs: shorter and smaller

src/components/navigation/Breadcrumbs.tsx, src/components/navigation/Footer.tsx, src/components/navigation/Header.tsx, src/components/navigation/Logo.tsx, src/components/navigation/Menu.tsx, src/components/navigation/MobileMenu.tsx, src/components/navigation/SearchInput.tsx, src/helper/csshelper.ts, src/theme.tsx
=> Header improvements

package.json, pages/[...slug].tsx, src/components/content/ContentTypes.tsx, src/components/navigation/MetaMenu.tsx, src/components/navigation/MobileMenuButton.tsx, src/components/navigation/MobileMetaMenu.tsx, src/metamenudata.tsx, yarn.lock
=> secondary navigation: placement and implementation

src/components/tags/StyledOl.tsx, src/components/tags/StyledTD.tsx, src/components/tags/StyledTH.tsx, src/components/tags/StyledTR.tsx, src/components/tags/StyledTable.tsx, src/components/tags/StyledUl.tsx
=> List and table styles

src/components/content/SpoilerContainer.tsx
=> Add makeMargin() to SpoilerContainer

pages/_document.js, src/components/navigation/SearchInput.tsx
First Proof of concept (mobile only)
=> Custom Search integration

pages/_colors.tsx, src/theme.tsx
check `/_colors` for an overview of all colors. 
I changed the way colors are defined to make it easier to understand how they relate and to make sure we don't loose the base colors.
todo: maybe find a better naming scheme, any ideas?
=> Rework colors

pages/[...slug].tsx
=> Return 404 on unknown alias

src/fetcher/serlo-api.tsx
=> add breadcrumbs to video, applet, course page

pages/[...slug].tsx, src/components/content/Exercise.tsx, src/components/content/Injection.tsx, src/components/content/LicenseNotice.tsx, src/fetcher/serlo-api.tsx, src/schema/articleRenderer.tsx
=> show license notice

src/fetcher/serlo-api.tsx
=> fallback to id if alias is missing

src/components/content/ArticlePage.tsx, src/components/navigation/CourseFooter.tsx, src/fetcher/serlo-api.tsx
=> add course title, hide "Weiter" on last page

pages/[...slug].tsx, src/fetcher/serlo-api.tsx
=> show hint to api route

src/schema/convertLegacyState.tsx
=> render geogebra instead of injection

.eslintrc.js, package.json, pages/[...slug].tsx, pages/_app.js, src/components/content/Geogebra.tsx, src/components/content/InputExercise.tsx, src/components/content/LicenseNotice.tsx, src/components/content/Notifications.tsx, src/components/content/ScMcExercise.tsx, src/components/content/Topic.tsx, src/components/navigation/CourseFooter.tsx, src/components/navigation/Footer.tsx, src/components/navigation/FooterNav.tsx, src/components/navigation/Menu.tsx, src/components/navigation/MetaMenu.tsx, src/components/navigation/MobileMetaMenu.tsx, src/components/navigation/SearchInput.tsx, src/components/navigation/Toolbox.tsx, src/components/tags/StyledH2.tsx, src/fetcher/createNavigation.tsx, src/fetcher/processResponse.tsx, src/fetcher/serlo-api.tsx, src/helper/csshelper.ts, src/schema/convertEdtrioState.tsx, src/schema/convertLegacyState.tsx, src/theme.tsx, yarn.lock
new command:
```
yarn lint
```
=> add eslint with typescript and react settings

pages/[...slug].tsx, src/components/content/CookieBar.tsx, src/components/content/Injection.tsx
to avoid possible name conflicts with existing code
=> /api/ -> /api/frontend/

pages/[...slug].tsx, public/_assets/img/subjects-blank.svg, src/components/content/Horizon.tsx, src/components/content/ImgCentered.tsx, src/components/content/Topic.tsx, src/components/landing/LandingSubjects.tsx, src/components/tags/StyledImg.tsx, src/schema/articleRenderer.tsx
PR so I can debug IE11 problems with the preview.
=> WIP: Browser fixes 

pages/_app.js, pages/_document.js, src/schema/articleRenderer.tsx, src/theme.tsx
improve letter spacing and correct bold and italic markup.
=> Minor font tweak

package.json, src/components/content/Exercise.tsx, src/components/content/ExerciseGroup.tsx, src/components/content/ExerciseNumbering.tsx, src/components/content/InputExercise.tsx, src/components/content/ScMcExercise.tsx, src/components/content/SpoilerBody.tsx, src/fetcher/createData.tsx, src/schema/articleRenderer.tsx, yarn.lock
=> Ex group improvements

src/fetcher/createData.tsx
*handle empty api fields correctly, fixes #172
=> Fix API Fetcher

src/components/content/Exercise.tsx, src/components/content/ScMcExercise.tsx, src/schema/convertEdtrioState.tsx
*properly convert state of exercises and solutions
=> Refactor conversion of exercises and solutions

src/schema/convertLegacyState.tsx
=> fix loading legacy image injections

src/schema/convertLegacyState.tsx
=> unescape ampersand

src/schema/articleRenderer.tsx, src/schema/convertEdtrioState.tsx
=> fallback for h6 to h5

src/schema/convertLegacyState.tsx
=> encode html entities in legacy converter

src/fetcher/createData.tsx, src/fetcher/query.ts
=> basic implementation of events

src/schema/convertLegacyState.tsx
=> correctly convert &nbsp;

src/fetcher/createData.tsx
=> handle curriculumTopicFolder correctly

src/schema/convertEdtrioState.tsx
handle case when paragraph in edtr-io contains only math elements (more than 1)
=> Improve edtr-io converter

src/components/content/Exercise.tsx, src/components/content/InputExercise.tsx, src/components/content/ScMcExercise.tsx, src/components/navigation/ShareModal.tsx
should fix last one `Prop ID did not match` in #186
also minor design fix for #221
closes #216
=> remove key warning, etc.

src/schema/articleRenderer.tsx
=> fix missing key warning

pages/[...slug].tsx, src/components/content/InputExercise.tsx, src/components/content/Topic.tsx, src/components/content/TopicLinkList.tsx, src/components/navigation/Breadcrumbs.tsx, src/components/navigation/ShareModal.tsx, src/components/navigation/ToolLine.tsx, src/fetcher/query.ts
=> Share menu feedback fixes etc.

src/fetcher/createData.tsx, src/fetcher/query.ts, src/schema/convertLegacyState.tsx
* fix missing space (legacy content), fixes #224
* fix missing title (applet) fixes #233
=> Two small fixes

pages/[...slug].tsx, src/components/NewsletterPopup.tsx
closes #181
Maybe not the react way, but this way we make sure code only loads if needed.
=> Add newsletter popup

external/LiteYouTubeEmbed.tsx, src/components/content/Video.tsx
Uses https://github.com/ibrahimcesar/react-lite-youtube-embed based on https://github.com/paulirish/lite-youtube-embed
just displays a preview image (and preconnects) until activated.
possible improvements in the future
- ~~check if `sddefault` thumbnail size actually exists and replace if not.~~
- even lazy load the preview image
- make use of webp images provided by yt
but should be good enough for now (224× faster if their claim is true :D)
closes #197
=> add youtube placeholder

src/schema/convertEdtrioState.tsx
=> add compat case in edtr-io converter

src/components/content/Equations.tsx, src/schema/articleRenderer.tsx, src/schema/convertEdtrioState.tsx
=> render equations

src/components/content/Code.tsx, src/schema/articleRenderer.tsx, src/schema/convertEdtrioState.tsx, src/schema/convertLegacyState.tsx
=> render code

pages/[...slug].tsx, src/components/PrettyLinksContext.tsx, src/components/content/ArticlePage.tsx, src/components/content/Link.tsx, src/fetcher/extractLinks.tsx, src/fetcher/processResponse.tsx, src/fetcher/query.ts, src/fetcher/serlo-api.tsx, src/schema/articleRenderer.tsx
=> Pretty links

pages/[...slug].tsx, src/components/content/ArticlePage.tsx, src/components/content/Topic.tsx, src/components/content/TopicLinkList.tsx
=> Content type icons improvements

src/pages/index.tsx
=> closes #256

external/LiteYouTubeEmbed.tsx, src/components/content/exercise.tsx, src/components/content/sc-mc-exercise.tsx, src/components/content/video.tsx, src/components/navigation/breadcrumbs.tsx, src/schema/article-renderer.tsx
Pair Programming session with @elbotho, resolved some `any`s 🎉
=> Type Refinements

src/schema/convert-edtr-io-state.tsx
=> fix missing feedback

src/components/content/exercise.tsx
on win10, the solution toogle has a unexpected line break in expanded state.
=> fix wrapping in solution toggle

src/components/landing/landing-about.tsx, src/components/landing/landing-subjects.tsx, src/pages/index.tsx, src/pages/spenden.tsx
closes #256 
@inyono thanks, I missed at least two. 
Do you see anything else here?
=> Landing page content (gender)

src/components/content/horizon.tsx, src/data/horizon.tsx, src/fetcher/process-response.tsx
=> Complete horizon data, add weight shuffle

src/components/content/cookie-bar.tsx
fixes #279 
just catch the exception for now...
=> catch exceptions with localStorage

src/schema/article-renderer.tsx
add more robust checking, fixes #309 and fixes #310
=> fix 500 pages

src/data/footer.tsx
=> use absolute url for API link

src/components/content/injection.tsx, src/components/content/link.tsx, src/components/pretty-links-context.tsx, src/fetcher/extract-links.tsx, src/fetcher/serlo-api.tsx
=> Pretty links for injections

src/components/content/entity.tsx
=> add schema.org

src/schema/convert-legacy-state.tsx
=> fix table converter

src/components/content/entity.tsx, src/components/content/equations.tsx, src/components/content/error-page.tsx, src/components/content/exercise.tsx, src/components/content/sc-mc-exercise.tsx, src/components/content/topic-link-list.tsx, src/components/content/topic.tsx, src/helper/css.ts, src/helper/header-by-content-type.ts, src/schema/article-renderer.tsx
No more errors in `/pages`, `/components`, `/helper`, `/data`.
(used two `// @ts-expect-error` comments in because of `EditorState` problems)
Remaining:
- `fetcher`: 319 Problems
- `schema`: 621 Problems
=> Another type session

src/components/content/entity.tsx, src/components/navigation/meta-menu.tsx, src/fetcher/extract-links.tsx, src/fetcher/serlo-api.tsx, src/pages/[...slug].tsx
closes #320
Link implementations are a bit messy now, see:
#329
=> Add PrettyLinks and Next Links to MetaMenu

src/pages/[...slug].tsx, src/pages/api/frontend/[...slug].tsx
=> fix double-encoding

src/fetcher/extract-links.tsx
@inyono I'll go ahead and merge this, as it currently breaks some pages 🥵
=> fix for #335

src/components/content/exercise.tsx, src/schema/article-renderer.tsx
=> fix @ts-expect-error

src/components/navigation/menu.tsx
making clearer what we need here and why it's not working yet ...
=> add slightly better types for tippy

src/components/content/injection.tsx, src/fetcher/create-breadcrumbs.tsx
=> Add cache to injections
